// Post-build: generate a service worker that precaches the real Vite manifest.
// Run automatically after `vite build`; no extra dependencies required.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const viteConfig = fs.readFileSync(path.join(projectRoot, 'vite.config.js'), 'utf8')
const baseMatch = viteConfig.match(/\bbase\s*:\s*['"`]([^'"`]*)['"`]/)
const rawBase = baseMatch ? baseMatch[1] : '/'

// Normalize to either '/' (root deployment) or '/subdir/' (sub-path deployment).
const strip = rawBase.replace(/^\.\//, '').replace(/^\/+|\/+$/g, '')
const BASE = strip === '' ? '/' : '/' + strip + '/'
const SCOPE_DIR = strip === '' ? '/' : '/' + strip

const dist = path.resolve(projectRoot, 'dist')
const manifestPath = path.join(dist, '.vite', 'manifest.json')
const indexPath = path.join(dist, 'index.html')
const indexAppPath = path.join(dist, 'index-app.html')

if (!fs.existsSync(dist)) {
  console.error('[pwa] dist/ not found — build first')
  process.exit(1)
}

if (!fs.existsSync(indexPath)) {
  console.error('[pwa] dist/index.html not found')
  process.exit(1)
}

// Collect every emitted JS/CSS/file from Vite's manifest.
let assetUrls = new Set()
if (fs.existsSync(manifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  for (const entry of Object.values(manifest)) {
    if (entry.file) assetUrls.add(BASE + entry.file.replace(/^\.?\//, ''))
    for (const css of entry.css || []) assetUrls.add(BASE + css.replace(/^\.?\//, ''))
    for (const asset of entry.assets || []) assetUrls.add(BASE + asset.replace(/^\.?\//, ''))
  }
}

// Fallback/extra: scan index.html for <script src> and <link href>.
const html = fs.readFileSync(indexPath, 'utf8')
const re = /(?:src|href)=["']([^"']+)["']/g
let m
while ((m = re.exec(html))) {
  const raw = m[1]
  if (!raw || /^data:|^https?:|^#/.test(raw)) continue
  // Strip a leading ./ and any base prefix, then add exactly one BASE.
  let clean = raw.split(/[?#]/)[0]
  if (BASE !== '/') clean = clean.replace(new RegExp('^\\.?' + BASE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), '')
  clean = clean.replace(/^\.?\//, '')
  if (/\.(js|css|woff2?|ttf|otf|eot|svg|png|jpe?g|webp|ico)$/i.test(clean) || clean.startsWith('assets/')) {
    assetUrls.add(BASE + clean)
  }
}

// Public PWA files that must be in the shell.
const shell = [
  BASE,
  BASE + 'index.html',
  BASE + 'index-app.html',
  BASE + 'manifest.json',
  BASE + 'icon-192.png',
  BASE + 'icon-512.png',
  BASE + 'service-worker.js',
]

const precache = [...new Set([...shell, ...assetUrls])].sort()
const version = 'ravand-' + Date.now().toString(36)
const shellUrl = BASE + 'index.html'
const shellAppUrl = BASE + 'index-app.html'

const sw = `// Generated by scripts/generate-sw.mjs — do not edit public/sw.js directly.
const CACHE = '${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const SHELL = ${JSON.stringify(shellUrl)};
const SHELL_APP = ${JSON.stringify(shellAppUrl)};
const ROOT = ${JSON.stringify(SCOPE_DIR)};
const SCOPE_PATH = ${JSON.stringify(SCOPE_DIR)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Download the shell and all hashed chunks in parallel.
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const response = await fetch(new Request(url, { cache: 'reload' }));
        if (response && response.ok) await cache.put(url, response);
      } catch (_) {}
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith('/api/')) return;
  if (/\\.(mp4|webm|mov|avi)$/i.test(url.pathname)) return;

  // SPA navigations (including iOS deep links) -> cached app shell offline.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        return await fetch(request);
      } catch (_) {
        // Try app shell first (for electron/app builds), then site shell
        const shell = await caches.match(SHELL_APP) || await caches.match(SHELL);
        if (shell) return shell;
        const root = await caches.match(ROOT);
        if (root) return root;
        return new Response('Offline: app shell not cached', {
          status: 503,
          headers: { 'Content-Type': 'text/plain; charset=utf-8' }
        });
      }
    })());
    return;
  }

  // Static assets: cache-first; never return HTML for JS/CSS/API.
  event.respondWith((async () => {
    const cached = await caches.match(request);
    if (cached) return cached;
    try {
      const response = await fetch(request);
      if (response && response.ok && url.pathname.startsWith(SCOPE_PATH + 'assets/')) {
        const cache = await caches.open(CACHE);
        await cache.put(request, response.clone());
      }
      return response;
    } catch (_) {
      return Response.error();
    }
  })());
});
`

fs.writeFileSync(path.join(dist, 'service-worker.js'), sw, 'utf8')

// Public sw.js is only a development fallback; the deployed build uses
// dist/service-worker.js generated above.
console.log('[pwa] generated dist/service-worker.js')
console.log('[pwa] precached ' + precache.length + ' files')
console.log('[pwa] ' + precache.join('\n       '))
